


-------------------------------------------------------------------------
--MHS PULL
-------------------------------------------------------------------------


CREATE OR REPLACE TEMPORARY TABLE COPA AS

SELECT  COPA.CUST_NUM AS CUST_ACCT_ID,
        SUM(SLS_QTY) AS "SLS_QTY",
        SUM(GROSS_SLS) AS "GROSS_SLS",
        SUM(CASE WHEN SLS_CTGRY_PRC_PROD_GRP IS NULL OR SLS_CTGRY_PRC_PROD_GRP = 'Bx' AND CMPNY_CD <> '8545' THEN GROSS_SLS ELSE 0 END) AS "BX_GROSS_SLS",
        SUM(CASE WHEN SLS_CTGRY_PRC_PROD_GRP = 'Gx' AND CMPNY_CD <> '8545' THEN GROSS_SLS ELSE 0 END) AS "GX_GROSS_SLS",
        SUM(CASE WHEN SLS_CTGRY_PRC_PROD_GRP = 'Sx' AND CMPNY_CD <> '8545' THEN GROSS_SLS ELSE 0 END) AS "SX_GROSS_SLS",
        SUM(CASE WHEN SLS_CTGRY_PRC_PROD_GRP = 'Bio' AND CMPNY_CD <> '8545' THEN GROSS_SLS ELSE 0 END) AS "BIO_GROSS_SLS",
        SUM(CASE WHEN SLS_CTGRY_PRC_PROD_GRP = 'Bx OTC' AND CMPNY_CD <> '8545' THEN GROSS_SLS ELSE 0 END) AS "OTC_GROSS_SLS",
        SUM(CASE WHEN CMPNY_CD = '8545' THEN GROSS_SLS ELSE 0 END) AS "MPB_GROSS_SLS",
        SUM(NET_REVENUE) AS "NET_REVENUE",
        SUM(VAR_EBIT) AS "EBIT",
        SUM(GROSS_PROFIT) AS "GROSS_PROFIT",
        SUM(CASE WHEN FPA_CUST_SEG_DESC LIKE '%MHS%' THEN GROSS_SLS ELSE 0 END) AS "MHS_GROSS_SLS",
        SUM(CASE WHEN FPA_CUST_SEG_DESC LIKE '%ISMC%' THEN GROSS_SLS ELSE 0 END) AS "CPH_GROSS_SLS",
        SUM(CASE WHEN FPA_CUST_SEG_DESC LIKE '%RNA%' THEN GROSS_SLS ELSE 0 END) AS "RNA_GROSS_SLS"
FROM    "SBX_PSAS_DB"."SBX_EA_ALL"."V_COPA_EA" COPA
JOIN    PRD_PSAS_DB.RPT.DIM_CUST_ACCT_CURR CUST
ON      LTRIM(COPA.CUST_NUM,'0') = LTRIM(CUST.CUST_ACCT_ID,'0') 
WHERE   CMPNY_CD IN ('8000','8545')
AND     POST_DT BETWEEN '2023-04-01' AND '2024-03-31'
AND     (FPA_CUST_SEG_DESC LIKE '%MHS%' OR FPA_CUST_SEG_DESC LIKE '%ISMC%' OR FPA_CUST_SEG_DESC LIKE '%RNA%')
--AND         LTRIM(CUST.CUST_ACCT_ID,'0') IN ()
 AND     CUST.ACTIVE_CUST_IND = 'A'
 AND        (CUST.CUST_BUS_TYP_CD IN ('07','08','09','16','27','30','32','33','34','35','36','37','38','39','41','42','43','44','46','47','48')
 OR         CUST.DIST_CHNL_TYP_CD IN ('20','30'))
AND         CUST.CUST_ACCT_NAM NOT LIKE '%TEMPLATE%'
AND         CUST.CUST_ACCT_NAM NOT LIKE '%REFERENCE%'
AND         CUST.CUST_ACCT_NAM NOT LIKE '%DO NOT USE%'
AND         CUST.CUST_ACCT_NAM NOT LIKE '% TEMP %'
AND         CUST.CUST_ACCT_NAM NOT LIKE '% MRX%'
AND         CUST.CUST_ACCT_NAM NOT LIKE '% TEST %'
AND         CUST.CUST_ACCT_NAM NOT LIKE '% XREF%'
AND         CUST.CUST_ACCT_NAM NOT LIKE '%EDI USE ONLY%'
GROUP BY COPA.CUST_NUM;



--HIERARCHY
CREATE OR REPLACE TEMPORARY TABLE HIERARCHY_PREP AS

SELECT      SFDC.CUST_ACCT_ID, 
            SFDC.SLSPRSN_EMPLY_ID,
            EID.EMPLY_NAME,
            CASE WHEN SFDC.SFDC_SLSPRSN_TITLE = 'AM' THEN 'EAE' 
                 WHEN SFDC.SFDC_SLSPRSN_TITLE = 'KAE' THEN 'DEA' 
                    ELSE SFDC.SFDC_SLSPRSN_TITLE END SFDC_SLSPRSN_TITLE,
            SFDC.SPRVSR_EMPLY_ID AS SPRVSR_EMPLY_ID,
            EID_SPRVSR.EMPLY_NAME AS SPRVSR_EMPLY_NAME,
            EID_SPRVSR.JOB_TITLE_DSCR AS SPRVSR_EMPLY_TITLE,
            SFDC.SPRVSR_LVL_2_EMPLY_ID AS SPRVSR_LVL_2_EMPLY_ID,
            EID_SPRVSR_TWO.EMPLY_NAME AS SPRVSR_LVL_2_EMPLY_NAME,
            EID_SPRVSR_TWO.JOB_TITLE_DSCR AS SPRVSR_LVL_2_EMPLY_TITLE,
            SFDC.SPRVSR_LVL_3_EMPLY_ID AS SPRVSR_LVL_3_EMPLY_ID,
            EID_SPRVSR_THREE.EMPLY_NAME AS SPRVSR_LVL_3_EMPLY_NAME,
            EID_SPRVSR_THREE.JOB_TITLE_DSCR AS SPRVSR_LVL_3_EMPLY_TITLE
FROM        PRD_PSAS_DB.APP.V_IF_RA_FACT_SFDC_REP_CUST_ACCT_CURR SFDC
JOIN        PRD_PSAS_DB.RPT.DIM_CUST_ACCT_CURR CUST
ON          SFDC.CUST_ACCT_ID = CUST.CUST_ACCT_ID
LEFT JOIN   PRD_PSAS_DB.EDWRPT.DIM_EMPLY_EID EID
ON          SFDC.SLSPRSN_EMPLY_ID = EID.EMPLY_ID
LEFT JOIN   PRD_PSAS_DB.EDWRPT.DIM_EMPLY_EID EID_SPRVSR
ON          SFDC.SPRVSR_EMPLY_ID = EID_SPRVSR.EMPLY_ID
LEFT JOIN   PRD_PSAS_DB.EDWRPT.DIM_EMPLY_EID EID_SPRVSR_TWO
ON          SFDC.SPRVSR_LVL_2_EMPLY_ID = EID_SPRVSR_TWO.EMPLY_ID
LEFT JOIN   PRD_PSAS_DB.EDWRPT.DIM_EMPLY_EID EID_SPRVSR_THREE
ON          SFDC.SPRVSR_LVL_3_EMPLY_ID = EID_SPRVSR_THREE.EMPLY_ID
WHERE       CUST.ACTIVE_CUST_IND = 'A'
AND         SFDC.SFDC_REP_SLS_TERR_ID <> 'N/A';


CREATE OR REPLACE TEMPORARY TABLE HIERARCHY AS

SELECT   * 
FROM    (SELECT CUST_ACCT_ID,SLSPRSN_EMPLY_ID, EMPLY_NAME, SFDC_SLSPRSN_TITLE, SPRVSR_EMPLY_ID, SPRVSR_EMPLY_NAME, SPRVSR_EMPLY_TITLE, ROW_NUMBER() OVER (PARTITION BY CUST_ACCT_ID ORDER BY SLSPRSN_EMPLY_ID ) AS ROW_NUM
         FROM HIERARCHY_PREP) T
WHERE   ROW_NUM = 1;



SELECT CUST.CUST_ACCT_ID AS CUST_ID,
       CUST.CUST_ACCT_NAM,
       INA_LOC_ID,
       CUST.CUST_BUS_TYP_DSCR,
       CUST.CUST_BUS_TYP_CD,
       CUST.CUST_CHN_ID,
       CUST.CUST_CHN_NAME,
       CUST.DEA_NUM,
       CUST.NABP_NUM,
       CUST.ACCT_CLAS_CD,
       CUST.ACCT_CLAS_DSCR,
       CUST.ACCT_340B_ID,
       CUST.NATL_GRP_CD,
       CUST.NATL_GRP_NAM,
       CUST.NATL_SUB_GRP_CD,
       CUST.NATL_SUB_GRP_NAM,
       CUST.MRKT_SEG_NAM,
       CUST.DIST_CHNL_TYP_CD,
       CUST.DIST_CHNL_TYP_DSCR,
       CUST.COMMON_GRP_ID,
       CUST.COMMON_GRP_NAME,
       CUST.COMMON_ENTITY_ID,
       CUST.COMMON_ENTITY_NAME,
       CUST.SLS_TERR_ID,
       CUST.HOME_DC_ID,
       HIERARCHY.EMPLY_NAME AS REP_NAME,
       HIERARCHY.SFDC_SLSPRSN_TITLE AS REP_TITLE,
       HIERARCHY.SPRVSR_EMPLY_NAME AS MANAGER_NAME,
       HIERARCHY.SPRVSR_EMPLY_TITLE AS MANAGER_TITLE,
       COALESCE(COPA.SLS_QTY,0) SLS_QTY,
       COALESCE(COPA. GROSS_SLS ,0)  GROSS_SLS ,
       COALESCE(COPA.BX_GROSS_SLS,0) BX_GROSS_SLS,
       COALESCE(COPA.GX_GROSS_SLS,0) GX_GROSS_SLS,
       COALESCE(COPA.SX_GROSS_SLS,0) SX_GROSS_SLS,
       COALESCE(COPA.BIO_GROSS_SLS,0) BIO_GROSS_SLS,
       COALESCE(COPA.OTC_GROSS_SLS,0) OTC_GROSS_SLS,
       COALESCE(COPA.MPB_GROSS_SLS,0) MPB_GROSS_SLS,
       COALESCE(COPA.NET_REVENUE,0) NET_REVENUE,
       COALESCE(COPA.EBIT,0) EBIT,
       COALESCE(COPA.GROSS_PROFIT,0) GROSS_PROFIT,
       COALESCE(COPA.MHS_GROSS_SLS,0) MHS_GROSS_SLS,
       COALESCE(COPA.CPH_GROSS_SLS,0) CPH_GROSS_SLS,
       COALESCE(COPA.RNA_GROSS_SLS,0) SA_GROSS_SLS
FROM   PRD_PSAS_DB.EDWRPT.DIM_CUST_ACCT_CURR CUST

JOIN COPA 
ON      LTRIM(COPA.CUST_ACCT_ID,'0') = LTRIM(CUST.CUST_ACCT_ID,'0') 

LEFT JOIN PRD_PSAS_DB.RPT.T_LOCATION_MAP
ON      LTRIM(COPA.CUST_ACCT_ID,'0') = LTRIM(T_LOCATION_MAP.CUST_ACCT_ID,'0')

LEFT JOIN HIERARCHY
ON      LTRIM(COPA.CUST_ACCT_ID,'0') = LTRIM(HIERARCHY.CUST_ACCT_ID,'0')

WHERE   CUST.ACTIVE_CUST_IND = 'A'
AND     (CUST.CUST_BUS_TYP_CD IN ('07','08','09','16','27','30','32','33','34','35','36','37','38','39','41','42','43','44','46','47','48')
OR     CUST.DIST_CHNL_TYP_CD IN ('20','30'))
AND     CUST.CUST_ACCT_NAM NOT LIKE '%TEMPLATE%'
AND     CUST.CUST_ACCT_NAM NOT LIKE '%REFERENCE%'
AND     CUST.CUST_ACCT_NAM NOT LIKE '%DO NOT USE%'
AND     CUST.CUST_ACCT_NAM NOT LIKE '% TEMP %'
AND     CUST.CUST_ACCT_NAM NOT LIKE '% MRX%'
AND     CUST.CUST_ACCT_NAM NOT LIKE '% TEST %'
AND     CUST.CUST_ACCT_NAM NOT LIKE '% XREF%'
AND     CUST.CUST_ACCT_NAM NOT LIKE '%EDI USE ONLY%';



-------------------------------------------------------------------------
--ACCT LIST PULL
-------------------------------------------------------------------------


CREATE OR REPLACE TEMPORARY TABLE COPA AS

SELECT  COPA.CUST_NUM AS CUST_ACCT_ID,
        SUM(SLS_QTY) AS "SLS_QTY",
        SUM(GROSS_SLS) AS "GROSS_SLS",
        SUM(CASE WHEN SLS_CTGRY_PRC_PROD_GRP IS NULL OR SLS_CTGRY_PRC_PROD_GRP = 'Bx' AND CMPNY_CD <> '8545' THEN GROSS_SLS ELSE 0 END) AS "BX_GROSS_SLS",
        SUM(CASE WHEN SLS_CTGRY_PRC_PROD_GRP = 'Gx' AND CMPNY_CD <> '8545' THEN GROSS_SLS ELSE 0 END) AS "GX_GROSS_SLS",
        SUM(CASE WHEN SLS_CTGRY_PRC_PROD_GRP = 'Sx' AND CMPNY_CD <> '8545' THEN GROSS_SLS ELSE 0 END) AS "SX_GROSS_SLS",
        SUM(CASE WHEN SLS_CTGRY_PRC_PROD_GRP = 'Bio' AND CMPNY_CD <> '8545' THEN GROSS_SLS ELSE 0 END) AS "BIO_GROSS_SLS",
        SUM(CASE WHEN SLS_CTGRY_PRC_PROD_GRP = 'Bx OTC' AND CMPNY_CD <> '8545' THEN GROSS_SLS ELSE 0 END) AS "OTC_GROSS_SLS",
        SUM(CASE WHEN CMPNY_CD = '8545' THEN GROSS_SLS ELSE 0 END) AS "MPB_GROSS_SLS",
        SUM(NET_REVENUE) AS "NET_REVENUE",
        SUM(VAR_EBIT) AS "EBIT",
        SUM(GROSS_PROFIT) AS "GROSS_PROFIT",
        SUM(CASE WHEN FPA_CUST_SEG_DESC LIKE '%MHS%' THEN GROSS_SLS ELSE 0 END) AS "MHS_GROSS_SLS",
        SUM(CASE WHEN FPA_CUST_SEG_DESC LIKE '%ISMC%' THEN GROSS_SLS ELSE 0 END) AS "CPH_GROSS_SLS",
        SUM(CASE WHEN FPA_CUST_SEG_DESC LIKE '%RNA%' THEN GROSS_SLS ELSE 0 END) AS "RNA_GROSS_SLS"
FROM    "SBX_PSAS_DB"."SBX_EA_ALL"."V_COPA_EA" COPA
JOIN    PRD_PSAS_DB.RPT.DIM_CUST_ACCT_CURR CUST
ON      LTRIM(COPA.CUST_NUM,'0') = LTRIM(CUST.CUST_ACCT_ID,'0') 
JOIN    SBX_PSAS_DB.SALES_OPS_GOV.T_TEMP_ACCT_LIST_4_18_2024_LOAD LOAD
ON      LTRIM(CUST.CUST_ACCT_ID,'0') = LTRIM(LOAD.CUST_ACCT_ID,'0') 
WHERE   CMPNY_CD IN ('8000','8545')
AND     POST_DT BETWEEN '2023-04-01' AND '2024-03-31'
AND     (FPA_CUST_SEG_DESC LIKE '%MHS%' OR FPA_CUST_SEG_DESC LIKE '%ISMC%' OR FPA_CUST_SEG_DESC LIKE '%RNA%')
GROUP BY COPA.CUST_NUM;


--HIERARCHY
CREATE OR REPLACE TEMPORARY TABLE HIERARCHY_PREP AS

SELECT      SFDC.CUST_ACCT_ID, 
            SFDC.SLSPRSN_EMPLY_ID,
            EID.EMPLY_NAME,
            CASE WHEN SFDC.SFDC_SLSPRSN_TITLE = 'AM' THEN 'EAE' 
                 WHEN SFDC.SFDC_SLSPRSN_TITLE = 'KAE' THEN 'DEA' 
                    ELSE SFDC.SFDC_SLSPRSN_TITLE END SFDC_SLSPRSN_TITLE,
            SFDC.SPRVSR_EMPLY_ID AS SPRVSR_EMPLY_ID,
            EID_SPRVSR.EMPLY_NAME AS SPRVSR_EMPLY_NAME,
            EID_SPRVSR.JOB_TITLE_DSCR AS SPRVSR_EMPLY_TITLE,
            SFDC.SPRVSR_LVL_2_EMPLY_ID AS SPRVSR_LVL_2_EMPLY_ID,
            EID_SPRVSR_TWO.EMPLY_NAME AS SPRVSR_LVL_2_EMPLY_NAME,
            EID_SPRVSR_TWO.JOB_TITLE_DSCR AS SPRVSR_LVL_2_EMPLY_TITLE,
            SFDC.SPRVSR_LVL_3_EMPLY_ID AS SPRVSR_LVL_3_EMPLY_ID,
            EID_SPRVSR_THREE.EMPLY_NAME AS SPRVSR_LVL_3_EMPLY_NAME,
            EID_SPRVSR_THREE.JOB_TITLE_DSCR AS SPRVSR_LVL_3_EMPLY_TITLE
FROM        PRD_PSAS_DB.APP.V_IF_RA_FACT_SFDC_REP_CUST_ACCT_CURR SFDC
JOIN        PRD_PSAS_DB.RPT.DIM_CUST_ACCT_CURR CUST
ON          SFDC.CUST_ACCT_ID = CUST.CUST_ACCT_ID
LEFT JOIN   PRD_PSAS_DB.EDWRPT.DIM_EMPLY_EID EID
ON          SFDC.SLSPRSN_EMPLY_ID = EID.EMPLY_ID
LEFT JOIN   PRD_PSAS_DB.EDWRPT.DIM_EMPLY_EID EID_SPRVSR
ON          SFDC.SPRVSR_EMPLY_ID = EID_SPRVSR.EMPLY_ID
LEFT JOIN   PRD_PSAS_DB.EDWRPT.DIM_EMPLY_EID EID_SPRVSR_TWO
ON          SFDC.SPRVSR_LVL_2_EMPLY_ID = EID_SPRVSR_TWO.EMPLY_ID
LEFT JOIN   PRD_PSAS_DB.EDWRPT.DIM_EMPLY_EID EID_SPRVSR_THREE
ON          SFDC.SPRVSR_LVL_3_EMPLY_ID = EID_SPRVSR_THREE.EMPLY_ID
WHERE       CUST.ACTIVE_CUST_IND = 'A'
AND         SFDC.SFDC_REP_SLS_TERR_ID <> 'N/A';


CREATE OR REPLACE TEMPORARY TABLE HIERARCHY AS

SELECT   * 
FROM    (SELECT CUST_ACCT_ID,SLSPRSN_EMPLY_ID, EMPLY_NAME, SFDC_SLSPRSN_TITLE, SPRVSR_EMPLY_ID, SPRVSR_EMPLY_NAME, SPRVSR_EMPLY_TITLE, ROW_NUMBER() OVER (PARTITION BY CUST_ACCT_ID ORDER BY SLSPRSN_EMPLY_ID ) AS ROW_NUM
         FROM HIERARCHY_PREP) T
WHERE   ROW_NUM = 1;



SELECT CUST.CUST_ACCT_ID AS CUST_ID,
       CUST.CUST_ACCT_NAM,
       INA_LOC_ID,
       CUST.CUST_BUS_TYP_DSCR,
       CUST.CUST_BUS_TYP_CD,
       CUST.CUST_CHN_ID,
       CUST.CUST_CHN_NAME,
       CUST.DEA_NUM,
       CUST.NABP_NUM,
       CUST.ACCT_CLAS_CD,
       CUST.ACCT_CLAS_DSCR,
       CUST.ACCT_340B_ID,
       CUST.NATL_GRP_CD,
       CUST.NATL_GRP_NAM,
       CUST.NATL_SUB_GRP_CD,
       CUST.NATL_SUB_GRP_NAM,
       CUST.MRKT_SEG_NAM,
       CUST.DIST_CHNL_TYP_CD,
       CUST.DIST_CHNL_TYP_DSCR,
       CUST.COMMON_GRP_ID,
       CUST.COMMON_GRP_NAME,
       CUST.COMMON_ENTITY_ID,
       CUST.COMMON_ENTITY_NAME,
       CUST.SLS_TERR_ID,
       CUST.HOME_DC_ID,
       HIERARCHY.EMPLY_NAME AS REP_NAME,
       HIERARCHY.SFDC_SLSPRSN_TITLE AS REP_TITLE,
       HIERARCHY.SPRVSR_EMPLY_NAME AS MANAGER_NAME,
       HIERARCHY.SPRVSR_EMPLY_TITLE AS MANAGER_TITLE,
       COALESCE(COPA.SLS_QTY,0) SLS_QTY,
       COALESCE(COPA. GROSS_SLS ,0)  GROSS_SLS ,
       COALESCE(COPA.BX_GROSS_SLS,0) BX_GROSS_SLS,
       COALESCE(COPA.GX_GROSS_SLS,0) GX_GROSS_SLS,
       COALESCE(COPA.SX_GROSS_SLS,0) SX_GROSS_SLS,
       COALESCE(COPA.BIO_GROSS_SLS,0) BIO_GROSS_SLS,
       COALESCE(COPA.OTC_GROSS_SLS,0) OTC_GROSS_SLS,
       COALESCE(COPA.MPB_GROSS_SLS,0) MPB_GROSS_SLS,
       COALESCE(COPA.NET_REVENUE,0) NET_REVENUE,
       COALESCE(COPA.EBIT,0) EBIT,
       COALESCE(COPA.GROSS_PROFIT,0) GROSS_PROFIT,
       COALESCE(COPA.MHS_GROSS_SLS,0) MHS_GROSS_SLS,
       COALESCE(COPA.CPH_GROSS_SLS,0) CPH_GROSS_SLS,
       COALESCE(COPA.RNA_GROSS_SLS,0) SA_GROSS_SLS
FROM   PRD_PSAS_DB.EDWRPT.DIM_CUST_ACCT_CURR CUST

JOIN COPA 
ON      LTRIM(COPA.CUST_ACCT_ID,'0') = LTRIM(CUST.CUST_ACCT_ID,'0') 

JOIN    SBX_PSAS_DB.SALES_OPS_GOV.T_TEMP_ACCT_LIST_4_18_2024_LOAD LOAD
ON      LTRIM(CUST.CUST_ACCT_ID,'0') = LTRIM(LOAD.CUST_ACCT_ID,'0') 

LEFT JOIN PRD_PSAS_DB.RPT.T_LOCATION_MAP
ON      LTRIM(COPA.CUST_ACCT_ID,'0') = LTRIM(T_LOCATION_MAP.CUST_ACCT_ID,'0')

LEFT JOIN HIERARCHY
ON      LTRIM(COPA.CUST_ACCT_ID,'0') = LTRIM(HIERARCHY.CUST_ACCT_ID,'0');



